=== CHPIYR2/ICIT2027/schemas/visibility_ids.v2.json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "investigation-visibility-v2"
    },
    "event_id": {
      "type": "string",
      "pattern": "^ev_[0-9a-f]{20}$"
    },
    "view": {
      "enum": [
        "E",
        "N",
        "EN"
      ]
    },
    "visible_record_ids": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^(?:p_[0-9a-f]{24}|m_[0-9a-f]{24}|e_[0-9a-f]{24}|a_[0-9a-f]{24})$"
      },
      "uniqueItems": true
    },
    "address_parents": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "pattern": "^(?:m_[0-9a-f]{24})$"
      },
      "propertyNames": {
        "type": "string",
        "pattern": "^(?:a_[0-9a-f]{24})$"
      }
    }
  },
  "required": [
    "schema_version",
    "event_id",
    "view",
    "visible_record_ids",
    "address_parents"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== CHPIYR2/ICIT2027/results/investigation-v2/B0/ev_d04a24cd3fe039e0f7c1/N/visibility.json
{
  "schema_version": "investigation-visibility-v2",
  "event_id": "ev_d04a24cd3fe039e0f7c1",
  "view": "N",
  "visible_record_ids": [
    "p_6e17154078475ac6adc26091",
    "p_de025e14fb841b650e261c50",
    "m_6139efbd97b1914a77143e29",
    "p_bbf13c866120a2881771094a",
    "p_14150795aba027bbc7e1910d",
    "m_23433d7dbc270f4d10647409",
    "p_0b1ac57838c47a0ed263aa06",
    "p_da7fa2cb96b5a797dda0f02b",
    "m_a3211b22e01007c22fae2884",
    "p_909d8f35cdd446817e81aeef",
    "p_575e82a84e3a9c833ba07ff8",
    "m_c43a8fae7b106b1ebb2aa5b6",
    "p_cc5583363dd2a9939b32307f",
    "p_5451cef472b0b97028536ce9",
    "m_185ce7acf5c577a3df860729",
    "p_68d39f39bbce9911a2ea2ed2",
    "p_404dd9bae2009d79a427f63f",
    "m_e6dcd40f16e45b979d456662",
    "p_3f90f9d8e7a0259a515f908e",
    "p_637c2bb6fea407795b1b4052",
    "m_30b8b4bb6bdbf8267a62939d",
    "p_5e5baa757b24c4c18f58cf1b",
    "p_4e62161247991e39e96ecc97",
    "m_efbc1a3cfb9240a10fc506c7",
    "p_479a9a90be128af889040584",
    "p_ebec995b834b016f472d70d6",
    "m_b4362ab2c5b38617122375c8",
    "p_4792d073efb2a083d7643940",
    "p_8234ccc2018e5a6eeac244f9",
    "m_86feaa3914cbc902911cba5a",
    "p_69c88d70c4c66299d51c7ad0",
    "p_43c55c0896658f32555e848f",
    "m_31c10db88836140d76e66a30",
    "p_f26737c410b4592f9b5cde0b",
    "p_7ef9cf2b4b59903b4c1bba2a",
    "m_69f0ad24381cb6d9c151ed8c",
    "p_06f44be8304d76f01b43f128",
    "p_cdd5743af6d007f4a6a8c8fe",
    "m_5e495a8cc530a1523cba7384",
    "p_ffd97d455ad519e374c65bcd",
    "p_3ef2b3606c5176e728614291",
    "m_b75d42518460eeb95e7a2ed8",
    "p_f265b39e21aba77d39375281",
    "p_c2ab4d8f3781e45a9834e6c3",
    "m_a9e46b26568608b128ec0590",
    "p_79993491e8c01ac8c42d3dc8",
    "p_122540b3d091c7095d3e7591",
    "m_616f07dcdf3f0faff420a7dc",
    "p_f5f68909dbe028b857ca1ee3",
    "p_727359739b8dc03cd75ba504",
    "m_ac9d1c1c1cecbfa31cd94afd",
    "p_131565d66281b5a327dadf2d",
    "p_310e557602261aa466176397",
    "m_9bbbcad5ab77f34b46a420eb",
    "p_06891d456a03e41762552a68",
    "p_f8be8321302317791d1e99ab",
    "m_b09255945ed09782ed17034f",
    "p_b6e10131c31730d1315f2ffc",
    "p_8b3916ee70b937b8d251a9a8",
    "m_41f9974ab74af45213f14c8f",
    "p_62924783e69d92d54efeb5e7",
    "p_21f8f3ce6f4ec7627d0a9632",
    "m_ba850bd43c727f597c336514",
    "p_072cde04f15ed850d00e9a39",
    "m_ac6007c66db2777bcedc777c",
    "p_ecd04619d4bde1c0f1ae5a89",
    "p_6dea8fe2eeec0f5669d07147",
    "p_9af18bc14a7dd9cdc7ffc927",
    "m_bacb4189030ee59c76f7eae5",
    "p_b5001a6433d70fb8499a1b96",
    "p_aab183c344ddb2eb3e7786e6",
    "m_e1e66cd9033594206dcd259b",
    "p_aa38da11adf81073d8506af3",
    "p_7c192b22ebd2191e88efbd6c",
    "m_db0827b857e7ff6dd8aa10b6",
    "p_66d3f23ab625809b68add809",
    "p_c077151f9ef8841a5ce32afd",
    "m_f06a4a8e144808f2e8ff9d3a",
    "p_9b0bef23a31d9ba367c59dd6",
    "p_b2fba5df80e72b91ca7e13e2",
    "m_a0faf126d26a69a324322f92",
    "p_7fb2bb2c7c5dd9853213c52f",
    "p_275d79553e9f71fa9bd4d8ff",
    "m_29218466b618eb5b93df179d",
    "p_03b1d4ca7f0f74109dddc87d",
    "p_c74db86d0353ec9c46e6fbc4",
    "m_1f2c793cdbd9831e9db8b6fd",
    "p_55dd08d4ea98c00214914546",
    "p_9dbfc148a5f04ebfb0af7063",
    "m_d1e9913dae36aa241a636aea",
    "p_4b049c0d28c65c40017a8460",
    "m_ce26cd56da2dbd33f93231c3",
    "p_111787ba2c99c6099936b6a3",
    "p_60f98d6e3e1e5357a4c01022",
    "m_f3c943cbe015334741ea1875",
    "p_42ff59e57dd88af56fc7a1cf",
    "p_600ce0af1a0422288b038c98",
    "p_8e7e64b7c4bdf633cebcfefe",
    "m_9d8cb95103a79ea199f2a876",
    "p_79f9c6ff1dd22d4b98d1c410",
    "p_9102658faeec683cfe13058c",
    "m_15ae074286ab5ccad9469bdd",
    "p_f70f992298017a0bde0a7dd0",
    "m_9a0050fcea2b04ca6cb56eff",
    "p_c3997b229b1dc3cd5bb73ed8",
    "p_1e8078167886ca8da3a3aa10",
    "p_9300a3790f7ef54d7bf33eda",
    "m_e0d96cf38fa558fc483b2314",
    "p_263571be2b3d9bbe43bef473",
    "p_a70bf92b3ea053f70f0ada33",
    "m_660fe808bf57f0c95acef8c7",
    "p_d211cebab7a49abcff600a2a",
    "p_5cce16af3d695c9602c56870",
    "m_d211087a8e032ab861dce102",
    "p_fd2dbbbd82b5b8e0c46511cc",
    "p_e327562f5cd6bf68a309e620",
    "m_4cec6156176817e91b809cf5",
    "p_0f895384f8250d5b3fbb0042",
    "m_9da4aa0a650558ac9be666bf",
    "p_21672af6f7e16b52fd1b6a5f",
    "p_0fc9c44f413618fc4dba1766",
    "m_732c4effa9f4792704a42b1b",
    "p_de4fc63486fa6c6f43309dae",
    "p_279089d5aa04dc3453cd4944",
    "p_b491f8b4f894c43959e81c9d",
    "m_70d8e6b902f7e36b025baeff",
    "p_bde3390a4ebe1623cb4cd265",
    "p_6cac10f4408b1fe0234236d1",
    "m_061b92904beb38544019496b",
    "p_17734e7c4a7dd226c2318d59",
    "m_a98ce7cf337c19a5e5440f9b",
    "p_ee3b174c2d5fd30b0d7801b7",
    "p_4a4ae80c0a3288fb19218d5e",
    "p_2c0b859c0b8eebe31addb59a",
    "m_f7e562fe1b4739bfa2ed0605",
    "p_7bd09f0bdcf7caa6618fa0e2",
    "p_e83ea9eb3ae4ecbcb4696fda",
    "m_d05ac31e63456db753343199",
    "p_70542857408710bacc077cd4",
    "p_d98f1254a5a61ce8808b44bf",
    "m_5190217c0937e11168fa091c",
    "p_19ca2aa8ed4b64fc5ef96328",
    "p_3ed86211a8cbd99fc8ee0a26",
    "m_35631a31639da61524127341",
    "p_3a07a265e61012addee3d8e5",
    "p_6a40d97ff4614a0278aa418e",
    "m_8cb330aebd62fd2ea5f54da0",
    "p_2ae9e84e5beb5d4d36561048",
    "p_96e2f12adb97f5b0c18fdd90",
    "m_a284ba6019303416b3371acc",
    "p_b06e3732f70728b6b7b7d6ce",
    "p_e98fe7e5f9a1f16ba7e7bcc4",
    "m_afa169bd7b5c7e3a0e30e51d",
    "p_f7ddd15d6fcf7d57d47b16d3",
    "p_bd856f001acf3a3a71eed16b",
    "p_92fdeed8815e7d5587648a80",
    "m_73da0d5019620950dc64bb60",
    "p_56843992469623b1bda19bfc",
    "p_cc6b1c71fcdf0dd0688b8ada",
    "m_10c465c403b34989126027af",
    "p_be7ac9c7b9969bf0bd80a650",
    "p_57d4ed9508308c1cdfc61fcc",
    "m_81cfee7d8598418f6868d049",
    "p_82a4b84067113c16b87a40ce",
    "p_9b3384a01b813d1f58fd5cd5",
    "m_ed249a6a0a6d830a25c5670a",
    "p_9a2cce6fe065f828c43f54a9",
    "p_16ff003b303bd9592caa4dee",
    "m_44a6dfde79571bab3003e9a7",
    "p_28db7c126bb726eacbec6e7a",
    "p_48be3dba0a65973de7879308",
    "m_0702bfe4680bbbf821208681",
    "p_63f713d50296c9dcdd17e89d",
    "p_2e82509132d1ad5a6763e457",
    "m_c07e59e200a50ecd11c10f82",
    "p_610c3fa6be1982bc54ac2a71",
    "p_a5a206c5a943270dc93d5e49",
    "m_83eaf657b14d9d52fd43a78a",
    "p_a3896d8ca0bf7c8756b25b9c",
    "p_64d8d453a8ec0ad190a65cec",
    "m_bca2e215c397c147c30cbcfd",
    "p_7c84acf59df299b5e9c173f9",
    "p_fa97ec7734d6fa7fd061badb",
    "m_50e004095bc3d0af91c852a0",
    "p_e85da4d319336ac5c8c6cc75",
    "p_097ccbb294abae7fe8406dd8",
    "m_62624541466b0fc5b4465d21",
    "p_691fb4bf8e6086068359cf8d",
    "m_0630fc98d660130e6cc3da29",
    "p_1847c100e2769d48d29a13db",
    "p_cb194c333bada471f58d0cef",
    "p_eb3e53291d05c3c1faae0d68",
    "m_4b6d67914a8e88e6405b0d87",
    "p_906e0f66fc9e43843ca7dced",
    "p_a24de4698d3df3ce93fd9f60",
    "m_3caa2bb7796565a95c7bdf89",
    "p_7b2059e9117c83c765afd183",
    "m_b84051841ab7fcb26e79d8ff",
    "p_ea8392973409bee19c214d50",
    "p_cf4fe2572160e2803088c9fc",
    "p_a40b1ab5dec93411f73b1bf1",
    "m_4e1b0fdf8056f3750302efec",
    "p_cc967ea96005829bdf151af8",
    "p_fd6758ed35ee99af728bed3b",
    "m_cda40d43249fefec778c276e",
    "p_c0a2fb778abf5ece5be9bedf",
    "p_be9351cfcfd21f40901eb698",
    "m_73a2b3336148e803ded145dc",
    "p_33ff26ca5b7bdd283d7faf02",
    "p_647e50e20b83f68d8ef0f57a",
    "m_36ca72a44992a493735a54bb",
    "p_f9f4bc2f9a7b6d1ec5ad698e",
    "p_5d047b8babf3e05000b1e313",
    "m_1c29dffe45e2e7b706978b0f",
    "p_0cf4cc22187134a8552698e3",
    "p_19832cf451bacbaad8723234",
    "m_df288fb8e7ccf63b0cd591da",
    "p_10fda7b3fde33a0956dbb143",
    "p_7acb95a98c703a326b9dd4f8",
    "m_267dc19eee6205c4b49f9db2",
    "p_26b398618eb927b10b6834e2",
    "p_81242ee0a262371cc8a254ba",
    "m_18944be952204f4e0c5f49cc",
    "p_68ebb0ab554f6e000c64bb78",
    "p_dd3322ec7a980d302d14158c",
    "m_47842689a15fe21fe21ef98c",
    "p_21033460293773c956bee9ff",
    "p_7d7338df605478a537822537",
    "m_e9289ea3265b540b9cd3de38",
    "p_f26fe9264dc27d67a2e68504",
    "p_247bb186adf7be79d1065b65",
    "m_8fed3810ef53b098fb3c87d9",
    "p_d8022fd944ab858370352911",
    "p_1c56dc2c485bc0c11c218d5f",
    "m_3cc222ddf92def47c0ce8b4f",
    "p_e304b52d8cfed78907db7587",
    "p_6f5e8f7d688a8362a117d820",
    "m_296039f6e4a25bebe3601aa7",
    "p_bb3779d56ca336f93c8d7a95",
    "p_6c59e3288e6a559688df39e7",
    "m_e0f09add0020895b76aec05d",
    "p_fb4c7665f3be9f386244e2ca",
    "p_f2e097f5867477c7d4f8cdc1",
    "m_81fa97201bbd6b9df99dadf6",
    "p_ee409240e402145b07742168",
    "p_47addf99681748b250f07d6e",
    "m_f14b75f051de56ed83fd7566",
    "p_96d759e1521a5d6d9f696998",
    "p_a435ad2dd5403c09b36614bc",
    "m_ff3d52e898aea8afecd7ffa9",
    "p_30b87ef69c336a8743212661",
    "p_acbe37a57fa80002dbc52f0c",
    "m_e380c15a52087cd0f5688f0d",
    "p_c49f77f98044c66e6d4f7c44",
    "p_e1f8cfdb831369a4803ad35e",
    "m_ae7650c10e5d2691491493fd",
    "p_1a8ecb85cf9572203d26f8ea",
    "p_4cc6b4d007d33e487942113f",
    "m_81f4ed0613e1617a7644bf13",
    "p_8335fd4cb4b4de5adeb5b0f3",
    "p_6f07ef30a1ff24d1f1e1dce6",
    "m_43489626e5467b8939d0adbe",
    "p_e4be636de06c900d05b7f523",
    "p_7061ccba1234792854e03f79",
    "m_85c7e17bc222a057087b582e",
    "p_c4a00d820fd9d278f92ebd55",
    "m_3f30126007a10139222d93bc",
    "p_ae7c6704de7a105b90872a0e",
    "p_80b6c578e3dbe7f44370b1b6",
    "p_46e51cb00dbc277cb9e0186a",
    "m_0b6e21e72e56f7d755e64626",
    "p_c6f05cd6381645fe31af785f",
    "p_ea7173f7e50c4f6bdc639dfe",
    "m_fb0397a7ea8cf9b6d42dbdfe",
    "p_bcd677d2368cf816ee7f8c48",
    "p_a35614cfb52d508d37b14dba",
    "m_c0fd5f1369481c8544776ca3",
    "p_5960feeaa44f7677a9c5780a",
    "p_8de42ce7a8cf7d35697be8a5",
    "m_eaa2732a6882f07c03d61da7",
    "p_650c3a72ea5bb52300f110d1",
    "p_768da66b2b93a56dcfdf682d",
    "m_9cab12b5100a36082d0a702b",
    "p_b47b0df8056467dc44a56818",
    "m_f02b9011703eb8510e9d3a54",
    "p_d72c12ffd22934b1eb73281b",
    "p_21bfac3df2adf6046e176c16",
    "p_43f788e2c891a329239f464a",
    "m_9e4dd66f8cdb7fb4fb138db1",
    "p_34964765ac492419a34ae18a",
